### ISSUE TITLE
Ant Building With Some Errors

### ISSUE THREAD

**Issue by timoshimmo** [unhurdle/spectrum-royale#75]
Hello

I was able to successfully make ant build but with some errors. Hence could not generate the target/Spectrum.swc file.
![spectrum_royale_ant_build_errors](https://user-images.githubusercontent.com/2452477/148108565-e36fedb2-4ca8-424b-b318-6992baabae44.png)

This is the error I get when I run ant in the Spectrum sub-folder. 

Pls what do I need to do?

**Comment by Harbs** [comment]
Like I mentioned in another issue, Spectrum is using new features in Royale that are only available in the latest nightly build.

These features make Spectrum components much more performant (which was why they were added).

You can either use the nightly build (which is not an official release, use at your own risk and other standard disclaimers). http://apacheroyaleci2.westus2.cloudapp.azure.com:8080/job/royale-asjs/lastSuccessfulBuild/artifact/out/ (or build yourself from source)

Or you can roll Spectrum back to an earlier version. This is the last commit which still supports 0.9.8: https://github.com/unhurdle/spectrum-royale/commit/024b7302af10abe24c24da6dd5b8f4d94b3073b7

**Comment by Harbs** [comment]
Actually, it looks like the latest nightly is from 8 days ago. I just triggered a build. Hopefully there will soon be a new one...

**Comment by timoshimmo** [comment]
Thank you... Works perfectly with that version of the commit.

**Comment by vinidiktov** [comment]
> Actually, it looks like the latest nightly is from 8 days ago. I just triggered a build. Hopefully there will soon be a new one...

Doesn't work with the December 27 build of Royale. There are no newer builds that I'm aware of.

**Comment by Harbs** [comment]
I'm not seeing the error.

In my build that's line 522 (instead of 500).

Make sure you clean your SpectrumBrowser project when you build.
