### ISSUE TITLE
Building issues

### ISSUE THREAD

**Issue by vinidiktov** [unhurdle/spectrum-royale#76]
I'm trying to build Spectrum with asconfigc with royale-0.9.8 and royale-0.9.9 on macOS Monterey from VS Code and from command line.

`> Executing task: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java -jar /Users/alexei/.vscode/extensions/bowlerhatllc.vscode-as3mxml-1.10.0/bin/asconfigc.jar --sdk /Users/alexei/Dev/royale/sdk/apache-royale-0.9.9-bin-js-swf/royale-asjs --debug=false --project /Users/alexei/Downloads/spectrum-royale-master/Spectrum/asconfig.json <

args:
+royalelib=/Users/alexei/Dev/royale/sdk/apache-royale-0.9.9-bin-js-swf/royale-asjs/frameworks
--debug=false
+configname=royale
--targets=SWF,JSRoyale
--external-library-path+=${royalelib}/libs
--external-library-path+=${royalelib}/../js/libs
--external-library-path+=libs
--js-external-library-path+=${royalelib}/../js/libs
--js-external-library-path+=${royalelib}/js/libs
--js-external-library-path+=libs
--load-config+=compile-config.xml
--js-load-config+=js-compile-config.xml
--warn-public-vars=false
--include-classes=Spectrum
--include-sources+=src
--source-path+=src
--output=target/Spectrum.swc
-js-output-optimization=skipAsCoercions
-js-dynamic-access-unknown-members=true
-allow-private-constructors=true
-js-complex-implicit-coercions=false
-js-vector-emulation-class=Array
-js-vector-index-checks=false
target:SWF
target:JSRoyale
COMPC
Loading configuration: /Users/alexei/Dev/royale/sdk/apache-royale-0.9.9-bin-js-swf/royale-asjs/frameworks/royale-config.xml
Loading configuration: /Users/alexei/Downloads/spectrum-royale-master/Spectrum/compile-config.xml

/Users/alexei/Downloads/spectrum-royale-master/Spectrum/src/com/unhurdle/spectrum/Group.as(19): col: 33 Error: Method marked override must override another method.

    override protected function requiresView():Boolean{
                                ^

/Users/alexei/Downloads/spectrum-royale-master/Spectrum/src/com/unhurdle/spectrum/Group.as(22): col: 33 Error: Method marked override must override another method.

    override protected function requiresController():Boolean{
                                ^

/Users/alexei/Downloads/spectrum-royale-master/Spectrum/src/com/unhurdle/spectrum/Group.as(25): col: 33 Error: Method marked override must override another method.

    override protected function requiresLayout():Boolean{
                                ^

/Users/alexei/Downloads/spectrum-royale-master/Spectrum/src/com/unhurdle/spectrum/ListViewForTable.as(12): col: 9 Warning: Definition org.apache.royale.html.util.getModelByType could not be found.

        import org.apache.royale.html.util.getModelByType;
               ^

/Users/alexei/Downloads/spectrum-royale-master/Spectrum/src/com/unhurdle/spectrum/ListViewForTable.as(123): col: 16 Error: Call to a possibly undefined method getModelByType.

                        listModel = getModelByType(_strand,ISelectionModel) as ISelectionModel;
                                    ^

/Users/alexei/Downloads/spectrum-royale-master/Spectrum/src/com/unhurdle/spectrum/SpectrumBase.as(19): col: 33 Error: Method marked override must override another method.

    override protected function requiresView():Boolean{
                                ^

/Users/alexei/Downloads/spectrum-royale-master/Spectrum/src/com/unhurdle/spectrum/SpectrumBase.as(22): col: 33 Error: Method marked override must override another method.

    override protected function requiresController():Boolean{
                                ^

/Users/alexei/Downloads/spectrum-royale-master/Spectrum/src/com/unhurdle/spectrum/renderers/DataItemRenderer.as(30): col: 33 Error: Method marked override must override another method.

    override protected function requiresView():Boolean{
                                ^

/Users/alexei/Downloads/spectrum-royale-master/Spectrum/src/com/unhurdle/spectrum/renderers/RemoveAllItemRendererForArrayListData.as(14): col: 9 Warning: Definition org.apache.royale.html.util.getModelByType could not be found.

        import org.apache.royale.html.util.getModelByType;
               ^

/Users/alexei/Downloads/spectrum-royale-master/Spectrum/src/com/unhurdle/spectrum/renderers/RemoveAllItemRendererForArrayListData.as(74): col: 29 Error: Call to a possibly undefined method getModelByType.

              _dataProviderModel = getModelByType(_strand,IDataProviderModel) as IDataProviderModel;
                                   ^

/Users/alexei/Downloads/spectrum-royale-master/Spectrum/src/com/unhurdle/spectrum/Group.as(19): col: 33 Method marked override must override another method.

    override protected function requiresView():Boolean{
                                ^

/Users/alexei/Downloads/spectrum-royale-master/Spectrum/src/com/unhurdle/spectrum/Group.as(22): col: 33 Method marked override must override another method.

    override protected function requiresController():Boolean{
                                ^

/Users/alexei/Downloads/spectrum-royale-master/Spectrum/src/com/unhurdle/spectrum/Group.as(25): col: 33 Method marked override must override another method.

    override protected function requiresLayout():Boolean{
                                ^

/Users/alexei/Downloads/spectrum-royale-master/Spectrum/src/com/unhurdle/spectrum/ListViewForTable.as(12): col: 9 Definition org.apache.royale.html.util.getModelByType could not be found.

        import org.apache.royale.html.util.getModelByType;
               ^

/Users/alexei/Downloads/spectrum-royale-master/Spectrum/src/com/unhurdle/spectrum/ListViewForTable.as(123): col: 16 Call to a possibly undefined method getModelByType.

                        listModel = getModelByType(_strand,ISelectionModel) as ISelectionModel;
                                    ^

/Users/alexei/Downloads/spectrum-royale-master/Spectrum/src/com/unhurdle/spectrum/SpectrumBase.as(19): col: 33 Method marked override must override another method.

    override protected function requiresView():Boolean{
                                ^

/Users/alexei/Downloads/spectrum-royale-master/Spectrum/src/com/unhurdle/spectrum/SpectrumBase.as(22): col: 33 Method marked override must override another method.

    override protected function requiresController():Boolean{
                                ^

/Users/alexei/Downloads/spectrum-royale-master/Spectrum/src/com/unhurdle/spectrum/renderers/DataItemRenderer.as(30): col: 33 Method marked override must override another method.

    override protected function requiresView():Boolean{
                                ^

/Users/alexei/Downloads/spectrum-royale-master/Spectrum/src/com/unhurdle/spectrum/renderers/RemoveAllItemRendererForArrayListData.as(14): col: 9 Definition org.apache.royale.html.util.getModelByType could not be found.

        import org.apache.royale.html.util.getModelByType;
               ^

/Users/alexei/Downloads/spectrum-royale-master/Spectrum/src/com/unhurdle/spectrum/renderers/RemoveAllItemRendererForArrayListData.as(74): col: 29 Call to a possibly undefined method getModelByType.

              _dataProviderModel = getModelByType(_strand,IDataProviderModel) as IDataProviderModel;
                                   ^

2.607371084 seconds
The terminal process "/Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java '-jar', '/Users/alexei/.vscode/extensions/bowlerhatllc.vscode-as3mxml-1.10.0/bin/asconfigc.jar', '--sdk', '/Users/alexei/Dev/royale/sdk/apache-royale-0.9.9-bin-js-swf/royale-asjs', '--debug=false', '--project', '/Users/alexei/Downloads/spectrum-royale-master/Spectrum/asconfig.json'" terminated with exit code: 3.
`

**Comment by vinidiktov** [comment]
Seems to be a duplicate of #75

**Comment by Harbs** [comment]
@vinidiktov I just fixed the nightly builds. Should work now.
